site_name: Cléa-API Documentation

site_url: https://WillIsback.github.io/clea-api/
repo_url: https://github.com/WillIsback/clea-api
repo_name: Cléa-API

docs_dir: docs
site_dir: site

nav:
  - Accueil: index.md
  - Introduction: main.md
  - Base de données: database.md
  - Schémas: schemas.md

  - Documentation des librairies:
      - askai:
          - RAG: lib/askai/rag_lib.md
      - doc_loader:
          - Extracteurs: lib/doc_loader/extractor_lib.md
          - Segmentation: lib/doc_loader/splitter_lib.md
      - pipeline:
          - Pipeline end-to-end: lib/pipeline/pipeline_lib.md
      - vectordb:
          - Opérations CRUD: lib/vectordb/crud_lib.md
          - Indexation vectorielle: lib/vectordb/index_lib.md
          - Recherche hybride: lib/stats/stats_computer_lib.md
      - stats:
          - Statistiques: lib/stats/stats_lib.md

  - Références API:
      - REST API:
          - Documentation Swagger: api/rest/rest_api.md
      - Références Python:
          - askai:
              - RAG: api/lib/askai/rag_references.md
          - doc_loader:
              - Extracteurs: api/lib/doc_loader/extractor_references.md
              - Segmentation: api/lib/doc_loader/splitter_references.md
          - pipeline:
              - Pipeline: api/lib/pipeline/pipeline_references.md
          - vectordb:
              - CRUD: api/lib/vectordb/crud_references.md
              - Indexation: api/lib/vectordb/index_references.md
              - Recherche: api/lib/vectordb/search_references.md
          - stats:
              - Statistiques: api/lib/stats/stats_computer_references.md

  - Intégrations:
      - JavaScript / TypeScript:
          - askai:
              - RAG: Integration/askai/rag_js.md
          - doc_loader:
              - Extraction de documents: Integration/doc_loader/doc_loader_js.md
          - pipeline:
              - Pipeline end-to-end: Integration/pipeline/pipeline_js.md
          - vectordb:
              - Opérations CRUD: Integration/vectordb/crud_js.md
              - Indexation: Integration/vectordb/index_js.md
              - Recherche: Integration/vectordb/search_js.md
          - stats:
              - Statistiques: Integration/stats/stats_computer_js.md

theme:
  name: readthedocs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            docstring_style: google
  - neoteroi.mkdocsoad:
      use_pymdownx: true

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables

extra_css:
  - css/mkdocsoad.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/WillIsback/clea-api

# Commande de déploiement GitHub Pages
# uv run mkdocs gh-deploy --force
