site_name: Cléa-API Documentation

nav:
  - Accueil: home.md
  - Introduction: main.md
  - Base de données: database.md
  - Schémas: schemas.md
  
  - Documentation des librairies:
      - doc_loader:
          - Extracteurs: lib/doc_loader/extractor_lib.md
          - Segmentation: lib/doc_loader/splitter_lib.md
      - pipeline:
          - Pipeline end-to-end: lib/pipeline/pipeline_lib.md
      - vectordb:
          - Opérations CRUD: lib/vectordb/crud_lib.md
          - Indexation vectorielle: lib/vectordb/index_lib.md
          - Recherche hybride: lib/vectordb/search_lib.md
  
  - Références API:
      - REST API:
          - Documentation Swagger: api/rest/rest_api.md
      - Références Python:
          - doc_loader:
              - Extracteurs: api/lib/doc_loader/extractor_references.md
              - Segmentation: api/lib/doc_loader/splitter_references.md
          - pipeline:
              - Pipeline: api/lib/pipeline/pipeline_references.md
          - vectordb:
              - CRUD: api/lib/vectordb/crud_references.md
              - Indexation: api/lib/vectordb/index_references.md
              - Recherche: api/lib/vectordb/search_references.md
  
  - Intégrations:
      - JavaScript / TypeScript: 
          - doc_loader:
              - Extraction de documents: Integration/doc_loader/doc_loader_js.md
          - pipeline:
              - Pipeline end-to-end: Integration/pipeline/pipeline_js.md
          - vectordb:
              - Opérations CRUD: Integration/vectordb/crud_js.md
              - Indexation: Integration/vectordb/index_js.md
              - Recherche: Integration/vectordb/search_js.md

theme:
  name: readthedocs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            docstring_style: google
  - neoteroi.mkdocsoad:
      use_pymdownx: true

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - tables
  - footnotes

extra_css:
  - css/mkdocsoad.css